const LEVELS = [
  {
    level: 0,
    requiredDownlines: 0,
    title: "Starter",
    icon: "starter",
    upgradeThreshold: 0,
    upgradeCost: 500,
    paymentsForUpgrade: [
      {
        payment_for_level: 0,
        payment_type: "Help",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 0,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 0,
        payment_type: "Direct",
        linkType: null,
        amount: 300,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 0,
      transactionsCount: 0,
      generateEarningLinks: {
        payment_for_level: 0,
        payment_type: "Upgrade",
        linkType: null,
        amount: 0,
      },
    },
  },
  {
    level: 1,
    requiredDownlines: 8,
    title: "Helper",
    icon: "helper",
    upgradeThreshold: 0,
    upgradeCost: 400,
    paymentsForUpgrade: [
      // {
      //   payment_for_level: 1,
      //   payment_type: "Passive",
      //   linkType: null,
      //   amount: 100,
      // },
      // {
      //   payment_for_level: 1,
      //   payment_type: "Passive",
      //   linkType: null,
      //   amount: 100,
      // },
      {
        payment_for_level: 1,
        payment_type: "Upgrade",
        linkType: 1,
        amount: 400,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 1600,
      transactionsCount: 4,
      generateEarningLinks: {
        payment_for_level: 1,
        payment_type: "Upgrade",
        linkType: 1,
        amount: 400,
      },
    },
  },

  {
    level: 2,
    requiredDownlines: 24,
    title: "Contributor",
    icon: "contributor",
    upgradeThreshold: 2400,
    upgradeCost: 1400,
    paymentsForUpgrade: [
      {
        payment_for_level: 2,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 2,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 2,
        payment_type: "Upgrade",
        linkType: 1,
        amount: 400,
      },
      {
        payment_for_level: 2,
        payment_type: "Upgrade",
        linkType: 2,
        amount: 800,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 6400,
      transactionsCount: 8,
      generateEarningLinks: {
        payment_for_level: 2,
        payment_type: "Upgrade",
        linkType: 2,
        amount: 800,
      },
    },
  },

  {
    level: 3,
    requiredDownlines: 64,
    title: "Supporter",
    icon: "supporter",
    upgradeThreshold: 10000,
    upgradeCost: 1600,
    paymentsForUpgrade: [
      {
        payment_for_level: 3,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 3,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 3,
        payment_type: "Upgrade",
        linkType: 1,
        amount: 400,
      },
      {
        payment_for_level: 3,
        payment_type: "Upgrade",
        linkType: 2,
        amount: 800,
      },
      {
        payment_for_level: 3,
        payment_type: "Upgrade",
        linkType: 3,
        amount: 1600,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 25600,
      transactionsCount: 16,
      generateEarningLinks: {
        payment_for_level: 3,
        payment_type: "Upgrade",
        linkType: 3,
        amount: 1600,
      },
    },
  },

  {
    level: 4,
    requiredDownlines: 128,
    title: "Rising Star",
    icon: "rising_star",
    upgradeThreshold: 26000,
    upgradeCost: 9000,
    paymentsForUpgrade: [
      {
        payment_for_level: 4,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 4,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 4,
        payment_type: "Upgrade",
        linkType: 1,
        amount: 400,
      },
      {
        payment_for_level: 4,
        payment_type: "Upgrade",
        linkType: 2,
        amount: 800,
      },
      {
        payment_for_level: 4,
        payment_type: "Upgrade",
        linkType: 3,
        amount: 1600,
      },
      {
        payment_for_level: 4,
        payment_type: "Upgrade",
        linkType: 4,
        amount: 6000,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 192000,
      transactionsCount: 32,
      generateEarningLinks: {
        payment_for_level: 4,
        payment_type: "Upgrade",
        linkType: 4,
        amount: 6000,
      },
    },
  },

  {
    level: 5,
    requiredDownlines: 256,
    title: "Success Star",
    icon: "success_star",
    upgradeThreshold: 60000,
    upgradeCost: 19000,
    paymentsForUpgrade: [
      {
        payment_for_level: 5,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 5,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 5,
        payment_type: "Upgrade",
        linkType: 1,
        amount: 400,
      },
      {
        payment_for_level: 5,
        payment_type: "Upgrade",
        linkType: 2,
        amount: 800,
      },
      {
        payment_for_level: 5,
        payment_type: "Upgrade",
        linkType: 3,
        amount: 1600,
      },
      {
        payment_for_level: 5,
        payment_type: "Upgrade",
        linkType: 4,
        amount: 6000,
      },
      {
        payment_for_level: 5,
        payment_type: "Upgrade",
        linkType: 5,
        amount: 10000,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 640000,
      transactionsCount: 64,
      generateEarningLinks: {
        payment_for_level: 5,
        payment_type: "Upgrade",
        linkType: 5,
        amount: 10000,
      },
    },
  },
  {
    level: 6,
    requiredDownlines: 512,
    title: "Growth Leader",
    icon: "growth_leader",
    upgradeThreshold: 100000,
    upgradeCost: 29000,
    paymentsForUpgrade: [
      {
        payment_for_level: 6,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 6,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 6,
        payment_type: "Upgrade",
        linkType: 1,
        amount: 400,
      },
      {
        payment_for_level: 6,
        payment_type: "Upgrade",
        linkType: 2,
        amount: 800,
      },
      {
        payment_for_level: 6,
        payment_type: "Upgrade",
        linkType: 3,
        amount: 1600,
      },
      {
        payment_for_level: 6,
        payment_type: "Upgrade",
        linkType: 4,
        amount: 6000,
      },
      {
        payment_for_level: 6,
        payment_type: "Upgrade",
        linkType: 5,
        amount: 10000,
      },
      {
        payment_for_level: 6,
        payment_type: "Upgrade",
        linkType: 6,
        amount: 10000,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 1280000,
      transactionsCount: 128,
      generateEarningLinks: {
        payment_for_level: 6,
        payment_type: "Upgrade",
        linkType: 6,
        amount: 10000,
      },
    },
  },
  {
    level: 7,
    requiredDownlines: 1024,
    title: "Master Leader",
    icon: "master_leader",
    upgradeThreshold: 100000,
    upgradeCost: 39000,
    paymentsForUpgrade: [
      {
        payment_for_level: 7,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 7,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 7,
        payment_type: "Upgrade",
        linkType: 1,
        amount: 400,
      },
      {
        payment_for_level: 7,
        payment_type: "Upgrade",
        linkType: 2,
        amount: 800,
      },
      {
        payment_for_level: 7,
        payment_type: "Upgrade",
        linkType: 3,
        amount: 1600,
      },
      {
        payment_for_level: 7,
        payment_type: "Upgrade",
        linkType: 4,
        amount: 6000,
      },
      {
        payment_for_level: 7,
        payment_type: "Upgrade",
        linkType: 5,
        amount: 10000,
      },
      {
        payment_for_level: 7,
        payment_type: "Upgrade",
        linkType: 6,
        amount: 10000,
      },
      {
        payment_for_level: 7,
        payment_type: "Upgrade",
        linkType: 7,
        amount: 10000,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 1280000,
      transactionsCount: 128,
      generateEarningLinks: {
        payment_for_level: 7,
        payment_type: "Upgrade",
        linkType: 7,
        amount: 10000,
      },
    },
  },
  {
    level: 8,
    requiredDownlines: 2048,
    title: "Champion",
    icon: "champion",
    upgradeThreshold: 100000,
    upgradeCost: 39000,
    paymentsForUpgrade: [
      {
        payment_for_level: 8,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 8,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 8,
        payment_type: "Upgrade",
        linkType: 1,
        amount: 400,
      },
      {
        payment_for_level: 8,
        payment_type: "Upgrade",
        linkType: 2,
        amount: 800,
      },
      {
        payment_for_level: 8,
        payment_type: "Upgrade",
        linkType: 3,
        amount: 1600,
      },
      {
        payment_for_level: 8,
        payment_type: "Upgrade",
        linkType: 4,
        amount: 6000,
      },
      {
        payment_for_level: 8,
        payment_type: "Upgrade",
        linkType: 6,
        amount: 10000,
      },
      {
        payment_for_level: 8,
        payment_type: "Upgrade",
        linkType: 7,
        amount: 10000,
      },
      {
        payment_for_level: 8,
        payment_type: "Upgrade",
        linkType: 8,
        amount: 10000,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 1280000,
      transactionsCount: 128,
      generateEarningLinks: {
        payment_for_level: 8,
        payment_type: "Upgrade",
        linkType: 8,
        amount: 10000,
      },
    },
  },
  {
    level: 9,
    requiredDownlines: 4096,
    title: "Grand Champion",
    icon: "grand_champion",
    upgradeThreshold: 100000,
    upgradeCost: 39000,
    paymentsForUpgrade: [
      {
        payment_for_level: 9,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 9,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 9,
        payment_type: "Upgrade",
        linkType: 1,
        amount: 400,
      },
      {
        payment_for_level: 9,
        payment_type: "Upgrade",
        linkType: 2,
        amount: 800,
      },
      {
        payment_for_level: 9,
        payment_type: "Upgrade",
        linkType: 3,
        amount: 1600,
      },
      {
        payment_for_level: 9,
        payment_type: "Upgrade",
        linkType: 4,
        amount: 6000,
      },
      {
        payment_for_level: 9,
        payment_type: "Upgrade",
        linkType: 7,
        amount: 10000,
      },
      {
        payment_for_level: 9,
        payment_type: "Upgrade",
        linkType: 8,
        amount: 10000,
      },
      {
        payment_for_level: 9,
        payment_type: "Upgrade",
        linkType: 9,
        amount: 10000,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 1280000,
      transactionsCount: 128,
      generateEarningLinks: {
        payment_for_level: 9,
        payment_type: "Upgrade",
        linkType: 9,
        amount: 10000,
      },
    },
  },
  {
    level: 10,
    requiredDownlines: 8192,
    title: "Super Elite",
    icon: "super_elite",
    upgradeThreshold: 100000,
    upgradeCost: 39000,
    paymentsForUpgrade: [
      {
        payment_for_level: 10,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 10,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 10,
        payment_type: "Upgrade",
        linkType: 1,
        amount: 400,
      },
      {
        payment_for_level: 10,
        payment_type: "Upgrade",
        linkType: 2,
        amount: 800,
      },
      {
        payment_for_level: 10,
        payment_type: "Upgrade",
        linkType: 3,
        amount: 1600,
      },
      {
        payment_for_level: 10,
        payment_type: "Upgrade",
        linkType: 4,
        amount: 6000,
      },
      {
        payment_for_level: 10,
        payment_type: "Upgrade",
        linkType: 8,
        amount: 10000,
      },
      {
        payment_for_level: 10,
        payment_type: "Upgrade",
        linkType: 9,
        amount: 10000,
      },
      {
        payment_for_level: 10,
        payment_type: "Upgrade",
        linkType: 10,
        amount: 10000,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 1280000,
      transactionsCount: 128,
      generateEarningLinks: {
        payment_for_level: 10,
        payment_type: "Upgrade",
        linkType: 10,
        amount: 10000,
      },
    },
  },
  {
    level: 11,
    requiredDownlines: 16384,
    title: "Mega Elite",
    icon: "mega_elite",
    upgradeThreshold: 100000,
    upgradeCost: 39000,
    paymentsForUpgrade: [
      {
        payment_for_level: 11,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 11,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 11,
        payment_type: "Upgrade",
        linkType: 1,
        amount: 400,
      },
      {
        payment_for_level: 11,
        payment_type: "Upgrade",
        linkType: 2,
        amount: 800,
      },
      {
        payment_for_level: 11,
        payment_type: "Upgrade",
        linkType: 3,
        amount: 1600,
      },
      {
        payment_for_level: 11,
        payment_type: "Upgrade",
        linkType: 4,
        amount: 6000,
      },
      {
        payment_for_level: 11,
        payment_type: "Upgrade",
        linkType: 9,
        amount: 10000,
      },
      {
        payment_for_level: 11,
        payment_type: "Upgrade",
        linkType: 10,
        amount: 10000,
      },
      {
        payment_for_level: 11,
        payment_type: "Upgrade",
        linkType: 11,
        amount: 10000,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 1280000,
      transactionsCount: 128,
      generateEarningLinks: {
        payment_for_level: 11,
        payment_type: "Upgrade",
        linkType: 11,
        amount: 10000,
      },
    },
  },
  {
    level: 12,
    requiredDownlines: 32768,
    title: "Royal Crown",
    icon: "royal_crown",
    upgradeThreshold: 100000,
    upgradeCost: 39000,
    paymentsForUpgrade: [
      {
        payment_for_level: 12,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 12,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 12,
        payment_type: "Upgrade",
        linkType: 1,
        amount: 400,
      },
      {
        payment_for_level: 12,
        payment_type: "Upgrade",
        linkType: 2,
        amount: 800,
      },
      {
        payment_for_level: 12,
        payment_type: "Upgrade",
        linkType: 3,
        amount: 1600,
      },
      {
        payment_for_level: 12,
        payment_type: "Upgrade",
        linkType: 4,
        amount: 6000,
      },
      {
        payment_for_level: 12,
        payment_type: "Upgrade",
        linkType: 10,
        amount: 10000,
      },
      {
        payment_for_level: 12,
        payment_type: "Upgrade",
        linkType: 11,
        amount: 10000,
      },
      {
        payment_for_level: 12,
        payment_type: "Upgrade",
        linkType: 12,
        amount: 10000,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 1280000,
      transactionsCount: 128,
      generateEarningLinks: {
        payment_for_level: 12,
        payment_type: "Upgrade",
        linkType: 12,
        amount: 10000,
      },
    },
  },
  {
    level: 13,
    requiredDownlines: 45000,
    title: "Supreme Royal",
    icon: "supreme_royal",
    upgradeThreshold: 100000,
    upgradeCost: 39000,
    paymentsForUpgrade: [
      {
        payment_for_level: 13,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 13,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 13,
        payment_type: "Upgrade",
        linkType: 1,
        amount: 400,
      },
      {
        payment_for_level: 13,
        payment_type: "Upgrade",
        linkType: 2,
        amount: 800,
      },
      {
        payment_for_level: 13,
        payment_type: "Upgrade",
        linkType: 3,
        amount: 1600,
      },
      {
        payment_for_level: 13,
        payment_type: "Upgrade",
        linkType: 4,
        amount: 6000,
      },
      {
        payment_for_level: 13,
        payment_type: "Upgrade",
        linkType: 11,
        amount: 10000,
      },
      {
        payment_for_level: 13,
        payment_type: "Upgrade",
        linkType: 12,
        amount: 10000,
      },
      {
        payment_for_level: 13,
        payment_type: "Upgrade",
        linkType: 13,
        amount: 10000,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 1280000,
      transactionsCount: 128,
      generateEarningLinks: {
        payment_for_level: 13,
        payment_type: "Upgrade",
        linkType: 13,
        amount: 10000,
      },
    },
  },
  {
    level: 14,
    requiredDownlines: 50000,
    title: "Executive Mentor",
    icon: "executive_mentor",
    upgradeThreshold: 100000,
    upgradeCost: 39000,
    paymentsForUpgrade: [
      {
        payment_for_level: 14,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 14,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 14,
        payment_type: "Upgrade",
        linkType: 1,
        amount: 400,
      },
      {
        payment_for_level: 14,
        payment_type: "Upgrade",
        linkType: 2,
        amount: 800,
      },
      {
        payment_for_level: 14,
        payment_type: "Upgrade",
        linkType: 3,
        amount: 1600,
      },
      {
        payment_for_level: 14,
        payment_type: "Upgrade",
        linkType: 4,
        amount: 6000,
      },
      {
        payment_for_level: 14,
        payment_type: "Upgrade",
        linkType: 12,
        amount: 10000,
      },
      {
        payment_for_level: 14,
        payment_type: "Upgrade",
        linkType: 13,
        amount: 10000,
      },
      {
        payment_for_level: 14,
        payment_type: "Upgrade",
        linkType: 14,
        amount: 10000,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 1280000,
      transactionsCount: 128,
      generateEarningLinks: {
        payment_for_level: 14,
        payment_type: "Upgrade",
        linkType: 14,
        amount: 10000,
      },
    },
  },
  {
    level: 15,
    requiredDownlines: 55000,
    title: "Chief Mentor",
    icon: "chief_mentor",
    upgradeThreshold: 100000,
    upgradeCost: 39000,
    paymentsForUpgrade: [
      {
        payment_for_level: 15,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 15,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 15,
        payment_type: "Upgrade",
        linkType: 1,
        amount: 400,
      },
      {
        payment_for_level: 15,
        payment_type: "Upgrade",
        linkType: 2,
        amount: 800,
      },
      {
        payment_for_level: 15,
        payment_type: "Upgrade",
        linkType: 3,
        amount: 1600,
      },
      {
        payment_for_level: 15,
        payment_type: "Upgrade",
        linkType: 4,
        amount: 6000,
      },
      {
        payment_for_level: 15,
        payment_type: "Upgrade",
        linkType: 13,
        amount: 10000,
      },
      {
        payment_for_level: 15,
        payment_type: "Upgrade",
        linkType: 14,
        amount: 10000,
      },
      {
        payment_for_level: 15,
        payment_type: "Upgrade",
        linkType: 15,
        amount: 10000,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 1280000,
      transactionsCount: 128,
      generateEarningLinks: {
        payment_for_level: 15,
        payment_type: "Upgrade",
        linkType: 15,
        amount: 10000,
      },
    },
  },
  {
    level: 16,
    requiredDownlines: 60000,
    title: "Team Captain",
    icon: "team_captain",
    upgradeThreshold: 100000,
    upgradeCost: 39000,
    paymentsForUpgrade: [
      {
        payment_for_level: 16,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 16,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 16,
        payment_type: "Upgrade",
        linkType: 1,
        amount: 400,
      },
      {
        payment_for_level: 16,
        payment_type: "Upgrade",
        linkType: 2,
        amount: 800,
      },
      {
        payment_for_level: 16,
        payment_type: "Upgrade",
        linkType: 3,
        amount: 1600,
      },
      {
        payment_for_level: 16,
        payment_type: "Upgrade",
        linkType: 4,
        amount: 6000,
      },
      {
        payment_for_level: 16,
        payment_type: "Upgrade",
        linkType: 14,
        amount: 10000,
      },
      {
        payment_for_level: 16,
        payment_type: "Upgrade",
        linkType: 15,
        amount: 10000,
      },
      {
        payment_for_level: 16,
        payment_type: "Upgrade",
        linkType: 16,
        amount: 10000,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 1280000,
      transactionsCount: 128,
      generateEarningLinks: {
        payment_for_level: 16,
        payment_type: "Upgrade",
        linkType: 16,
        amount: 10000,
      },
    },
  },
  {
    level: 17,
    requiredDownlines: 65000,
    title: "Team Director",
    icon: "team_director",
    upgradeThreshold: 100000,
    upgradeCost: 39000,
    paymentsForUpgrade: [
      {
        payment_for_level: 17,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 17,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 17,
        payment_type: "Upgrade",
        linkType: 1,
        amount: 400,
      },
      {
        payment_for_level: 17,
        payment_type: "Upgrade",
        linkType: 2,
        amount: 800,
      },
      {
        payment_for_level: 17,
        payment_type: "Upgrade",
        linkType: 3,
        amount: 1600,
      },
      {
        payment_for_level: 17,
        payment_type: "Upgrade",
        linkType: 4,
        amount: 6000,
      },
      {
        payment_for_level: 17,
        payment_type: "Upgrade",
        linkType: 15,
        amount: 10000,
      },
      {
        payment_for_level: 17,
        payment_type: "Upgrade",
        linkType: 16,
        amount: 10000,
      },
      {
        payment_for_level: 17,
        payment_type: "Upgrade",
        linkType: 17,
        amount: 10000,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 1280000,
      transactionsCount: 128,
      generateEarningLinks: {
        payment_for_level: 17,
        payment_type: "Upgrade",
        linkType: 17,
        amount: 10000,
      },
    },
  },
  {
    level: 18,
    requiredDownlines: 70000,
    title: "Executive Director",
    icon: "executive_director",
    upgradeThreshold: 100000,
    upgradeCost: 39000,
    paymentsForUpgrade: [
      {
        payment_for_level: 18,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 18,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 18,
        payment_type: "Upgrade",
        linkType: 1,
        amount: 400,
      },
      {
        payment_for_level: 18,
        payment_type: "Upgrade",
        linkType: 2,
        amount: 800,
      },
      {
        payment_for_level: 18,
        payment_type: "Upgrade",
        linkType: 3,
        amount: 1600,
      },
      {
        payment_for_level: 18,
        payment_type: "Upgrade",
        linkType: 4,
        amount: 6000,
      },
      {
        payment_for_level: 18,
        payment_type: "Upgrade",
        linkType: 16,
        amount: 10000,
      },
      {
        payment_for_level: 18,
        payment_type: "Upgrade",
        linkType: 17,
        amount: 10000,
      },
      {
        payment_for_level: 18,
        payment_type: "Upgrade",
        linkType: 18,
        amount: 10000,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 1280000,
      transactionsCount: 128,
      generateEarningLinks: {
        payment_for_level: 18,
        payment_type: "Upgrade",
        linkType: 18,
        amount: 10000,
      },
    },
  },
  {
    level: 19,
    requiredDownlines: 75000,
    title: "Zone Director",
    icon: "zone_director",
    upgradeThreshold: 100000,
    upgradeCost: 39000,
    paymentsForUpgrade: [
      {
        payment_for_level: 19,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 19,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 19,
        payment_type: "Upgrade",
        linkType: 1,
        amount: 400,
      },
      {
        payment_for_level: 19,
        payment_type: "Upgrade",
        linkType: 2,
        amount: 800,
      },
      {
        payment_for_level: 19,
        payment_type: "Upgrade",
        linkType: 3,
        amount: 1600,
      },
      {
        payment_for_level: 19,
        payment_type: "Upgrade",
        linkType: 4,
        amount: 6000,
      },
      {
        payment_for_level: 19,
        payment_type: "Upgrade",
        linkType: 17,
        amount: 10000,
      },
      {
        payment_for_level: 19,
        payment_type: "Upgrade",
        linkType: 18,
        amount: 10000,
      },
      {
        payment_for_level: 19,
        payment_type: "Upgrade",
        linkType: 19,
        amount: 10000,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 1280000,
      transactionsCount: 128,
      generateEarningLinks: {
        payment_for_level: 19,
        payment_type: "Upgrade",
        linkType: 19,
        amount: 10000,
      },
    },
  },
  {
    level: 20,
    requiredDownlines: 80000,
    title: "Global Director",
    icon: "global_director",
    upgradeThreshold: 100000,
    upgradeCost: 39000,
    paymentsForUpgrade: [
      {
        payment_for_level: 20,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 20,
        payment_type: "Passive",
        linkType: null,
        amount: 100,
      },
      {
        payment_for_level: 20,
        payment_type: "Upgrade",
        linkType: 1,
        amount: 400,
      },
      {
        payment_for_level: 20,
        payment_type: "Upgrade",
        linkType: 2,
        amount: 800,
      },
      {
        payment_for_level: 20,
        payment_type: "Upgrade",
        linkType: 3,
        amount: 1600,
      },
      {
        payment_for_level: 20,
        payment_type: "Upgrade",
        linkType: 4,
        amount: 6000,
      },
      {
        payment_for_level: 20,
        payment_type: "Upgrade",
        linkType: 18,
        amount: 10000,
      },
      {
        payment_for_level: 20,
        payment_type: "Upgrade",
        linkType: 19,
        amount: 10000,
      },
      {
        payment_for_level: 20,
        payment_type: "Upgrade",
        linkType: 20,
        amount: 10000,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 1280000,
      transactionsCount: 128,
      generateEarningLinks: {
        payment_for_level: 20,
        payment_type: "Upgrade",
        linkType: 20,
        amount: 10000,
      },
    },
  },
];

const defaultLevels = [
  {
    label: "Starter",
    value: 0,
    assignedUser: null,
  },
  {
    label: "Helper",
    value: 1,
    assignedUser: null,
  },
  {
    label: "Contributor",
    value: 2,
    assignedUser: null,
  },
  {
    label: "Supporter",
    value: 3,
    assignedUser: null,
  },
  {
    label: "Rising Star",
    value: 4,
    assignedUser: null,
  },
  {
    label: "Success Star",
    value: 5,
    assignedUser: null,
  },
  {
    label: "Growth Leader",
    value: 6,
    assignedUser: null,
  },
  {
    label: "Master Leader",
    value: 7,
    assignedUser: null,
  },
  {
    label: "Champion",
    value: 8,
    assignedUser: null,
  },
  {
    label: "Grand Champion",
    value: 9,
    assignedUser: null,
  },
  {
    label: "Super Elite",
    value: 10,
    assignedUser: null,
  },
  {
    label: "Mega Elite",
    value: 11,
    assignedUser: null,
  },
  {
    label: "Royal Crown",
    value: 12,
    assignedUser: null,
  },
  {
    label: "Supreme Royal",
    value: 13,
    assignedUser: null,
  },
  {
    label: "Executive Mentor",
    value: 14,
    assignedUser: null,
  },
  {
    label: "Chief Mentor",
    value: 15,
    assignedUser: null,
  },
  {
    label: "Team Captain",
    value: 16,
    assignedUser: null,
  },
  {
    label: "Team Director",
    value: 17,
    assignedUser: null,
  },
  {
    label: "Executive Director",
    value: 18,
    assignedUser: null,
  },
  {
    label: "Zone Director",
    value: 19,
    assignedUser: null,
  },
  {
    label: "Global Director",
    value: 20,
    assignedUser: null,
  },
];

const defaultWalletTransferRatio = [
  { level: 0, e_cash: "33%", upgrade: "67%" },
  { level: 1, e_cash: "12%", upgrade: "88%" },
  { level: 2, e_cash: "50%", upgrade: "50%" },
  { level: 3, e_cash: "50%", upgrade: "50%" },
  { level: 4, e_cash: "50%", upgrade: "50%" },
  { level: 5, e_cash: "60%", upgrade: "40%" },
  { level: 6, e_cash: "70%", upgrade: "30%" },
  { level: 7, e_cash: "80%", upgrade: "20%" },
  { level: 8, e_cash: "80%", upgrade: "20%" },
  { level: 9, e_cash: "80%", upgrade: "20%" },
  { level: 10, e_cash: "80%", upgrade: "20%" },
  { level: 11, e_cash: "80%", upgrade: "20%" },
  { level: 12, e_cash: "80%", upgrade: "20%" },
  { level: 13, e_cash: "80%", upgrade: "20%" },
  { level: 14, e_cash: "80%", upgrade: "20%" },
  { level: 15, e_cash: "80%", upgrade: "20%" },
  { level: 16, e_cash: "80%", upgrade: "20%" },
  { level: 17, e_cash: "80%", upgrade: "20%" },
  { level: 18, e_cash: "80%", upgrade: "20%" },
  { level: 19, e_cash: "80%", upgrade: "20%" },
  { level: 20, e_cash: "80%", upgrade: "20%" },
];

const receivingPaymetAccordingLeg = [
  { level: 0, left_leg: 0, right_leg: 0, totalLinks: 0 },
  { level: 1, left_leg: 2, right_leg: 2, totalLinks: 4 },
  { level: 2, left_leg: 4, right_leg: 4, totalLinks: 8 },
  { level: 3, left_leg: 8, right_leg: 8, totalLinks: 16 },
  { level: 4, left_leg: 16, right_leg: 16, totalLinks: 32 },
  { level: 5, left_leg: 32, right_leg: 32, totalLinks: 64 },
  { level: 6, left_leg: 64, right_leg: 64, totalLinks: 128 },
  { level: 7, left_leg: 64, right_leg: 64, totalLinks: 128 },
  { level: 8, left_leg: 64, right_leg: 64, totalLinks: 128 },
  { level: 9, left_leg: 64, right_leg: 64, totalLinks: 128 },
  { level: 10, left_leg: 64, right_leg: 64, totalLinks: 128 },
  { level: 11, left_leg: 64, right_leg: 64, totalLinks: 128 },
  { level: 12, left_leg: 64, right_leg: 64, totalLinks: 128 },
  { level: 13, left_leg: 64, right_leg: 64, totalLinks: 128 },
  { level: 14, left_leg: 64, right_leg: 64, totalLinks: 128 },
  { level: 15, left_leg: 64, right_leg: 64, totalLinks: 128 },
  { level: 16, left_leg: 64, right_leg: 64, totalLinks: 128 },
  { level: 17, left_leg: 64, right_leg: 64, totalLinks: 128 },
  { level: 18, left_leg: 64, right_leg: 64, totalLinks: 128 },
  { level: 19, left_leg: 64, right_leg: 64, totalLinks: 128 },
  { level: 20, left_leg: 64, right_leg: 64, totalLinks: 128 },
];

const directRewardsList = [
  {
    totalDirect: 4,
    earningsAfterUpgrade: [
      {
        transactionsCount: 6,
        generateEarningLinks: {
          payment_for_level: 1,
          payment_type: "Upgrade",
          linkType: 1,
          amount: 400,
        },
      },
      {
        transactionsCount: 12,
        generateEarningLinks: {
          payment_for_level: 2,
          payment_type: "Upgrade",
          linkType: 2,
          amount: 800,
        },
      },
      {
        transactionsCount: 24,
        generateEarningLinks: {
          payment_for_level: 3,
          payment_type: "Upgrade",
          linkType: 3,
          amount: 1600,
        },
      },
    ],
  },
  {
    totalDirect: 6,
    earningsAfterUpgrade: [
      {
        transactionsCount: 8,
        generateEarningLinks: {
          payment_for_level: 1,
          payment_type: "Upgrade",
          linkType: 1,
          amount: 400,
        },
      },
      {
        transactionsCount: 16,
        generateEarningLinks: {
          payment_for_level: 2,
          payment_type: "Upgrade",
          linkType: 2,
          amount: 800,
        },
      },
      {
        transactionsCount: 32,
        generateEarningLinks: {
          payment_for_level: 3,
          payment_type: "Upgrade",
          linkType: 3,
          amount: 1600,
        },
      },
    ],
  },
  {
    totalDirect: 8,
    earningsAfterUpgrade: [
      {
        transactionsCount: 10,
        generateEarningLinks: {
          payment_for_level: 1,
          payment_type: "Upgrade",
          linkType: 1,
          amount: 400,
        },
      },
      {
        transactionsCount: 20,
        generateEarningLinks: {
          payment_for_level: 2,
          payment_type: "Upgrade",
          linkType: 2,
          amount: 800,
        },
      },
      {
        transactionsCount: 40,
        generateEarningLinks: {
          payment_for_level: 3,
          payment_type: "Upgrade",
          linkType: 3,
          amount: 1600,
        },
      },
    ],
  },
  {
    totalDirect: 10,
    earningsAfterUpgrade: [
      {
        transactionsCount: 12,
        generateEarningLinks: {
          payment_for_level: 1,
          payment_type: "Upgrade",
          linkType: 1,
          amount: 400,
        },
      },
      {
        transactionsCount: 24,
        generateEarningLinks: {
          payment_for_level: 2,
          payment_type: "Upgrade",
          linkType: 2,
          amount: 800,
        },
      },
      {
        transactionsCount: 48,
        generateEarningLinks: {
          payment_for_level: 3,
          payment_type: "Upgrade",
          linkType: 3,
          amount: 1600,
        },
      },
    ],
  },
  {
    totalDirect: 20,
    earningsAfterUpgrade: [
      {
        transactionsCount: 25,
        generateEarningLinks: {
          payment_for_level: 1,
          payment_type: "Upgrade",
          linkType: 1,
          amount: 400,
        },
      },
      {
        transactionsCount: 50,
        generateEarningLinks: {
          payment_for_level: 2,
          payment_type: "Upgrade",
          linkType: 2,
          amount: 800,
        },
      },
      {
        transactionsCount: 100,
        generateEarningLinks: {
          payment_for_level: 3,
          payment_type: "Upgrade",
          linkType: 3,
          amount: 1600,
        },
      },
    ],
  },
  {
    totalDirect: 50,
    earningsAfterUpgrade: [
      {
        transactionsCount: 50,
        generateEarningLinks: {
          payment_for_level: 1,
          payment_type: "Upgrade",
          linkType: 1,
          amount: 400,
        },
      },
      {
        transactionsCount: 100,
        generateEarningLinks: {
          payment_for_level: 2,
          payment_type: "Upgrade",
          linkType: 2,
          amount: 800,
        },
      },
      {
        transactionsCount: 200,
        generateEarningLinks: {
          payment_for_level: 3,
          payment_type: "Upgrade",
          linkType: 3,
          amount: 1600,
        },
      },
    ],
  },
  {
    totalDirect: 100,
    earningsAfterUpgrade: [
      {
        transactionsCount: 100,
        generateEarningLinks: {
          payment_for_level: 1,
          payment_type: "Upgrade",
          linkType: 1,
          amount: 400,
        },
      },
      {
        transactionsCount: 200,
        generateEarningLinks: {
          payment_for_level: 2,
          payment_type: "Upgrade",
          linkType: 2,
          amount: 800,
        },
      },
      {
        transactionsCount: 400,
        generateEarningLinks: {
          payment_for_level: 3,
          payment_type: "Upgrade",
          linkType: 3,
          amount: 1600,
        },
      },
    ],
  },
];

const ePoolEntryArray = [
  {
    level: 1,
    upgrade: [
      {
        payment_for_level: 1,
        payment_type: "E_Pool_Upgrade",
        amount: 500,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 1500,
      transactionsCount: 3,
      generateEarningLinks: {
        payment_for_level: 1,
        payment_type: "E_Pool_Upgrade",
        amount: 500,
      },
    },
  },
  {
    level: 2,
    upgrade: [
      {
        payment_for_level: 2,
        payment_type: "E_Pool_Upgrade",
        amount: 1000,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 3000,
      transactionsCount: 3,
      generateEarningLinks: {
        payment_for_level: 2,
        payment_type: "E_Pool_Upgrade",
        amount: 1000,
      },
    },
  },
  {
    level: 3,
    upgrade: [
      {
        payment_for_level: 3,
        payment_type: "E_Pool_Upgrade",
        amount: 2000,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 6000,
      transactionsCount: 3,
      generateEarningLinks: {
        payment_for_level: 3,
        payment_type: "E_Pool_Upgrade",
        amount: 2000,
      },
    },
  },
  {
    level: 4,
    upgrade: [
      {
        payment_for_level: 4,
        payment_type: "E_Pool_Upgrade",
        amount: 4000,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 12000,
      transactionsCount: 3,
      generateEarningLinks: {
        payment_for_level: 4,
        payment_type: "E_Pool_Upgrade",
        amount: 4000,
      },
    },
  },
  {
    level: 5,
    upgrade: [
      {
        payment_for_level: 5,
        payment_type: "E_Pool_Upgrade",
        amount: 8000,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 32000,
      transactionsCount: 3,
      generateEarningLinks: {
        payment_for_level: 5,
        payment_type: "E_Pool_Upgrade",
        amount: 8000,
      },
    },
  },
  {
    level: 6,
    upgrade: [
      {
        payment_for_level: 6,
        payment_type: "E_Pool_Upgrade",
        amount: 16000,
      },
    ],
    earningsAfterUpgrade: {
      totalEarnings: 64000,
      transactionsCount: 3,
      generateEarningLinks: {
        payment_for_level: 6,
        payment_type: "E_Pool_Upgrade",
        amount: 16000,
      },
    },
  },
  // {
  //   level: 7,
  //   upgrade: [
  //     {
  //       payment_for_level: 7,
  //       payment_type: "E_Pool_Upgrade",
  //       amount: 32000,
  //     },
  //   ],
  //   earningsAfterUpgrade: {
  //     totalEarnings: 128000,
  //     transactionsCount: 3,
  //     generateEarningLinks: {
  //       payment_for_level: 7,
  //       payment_type: "E_Pool_Upgrade",
  //       amount: 32000,
  //     },
  //   },
  // },
];

module.exports = {
  LEVELS,
  defaultLevels,
  defaultWalletTransferRatio,
  directRewardsList,
  ePoolEntryArray,
};
